dist: trusty
sudo: false
language: cpp
compiler: clang
env:
  - COMPILER=clang-3.9
  - CXX=clang++-3.9
  - CC=clang-3.9
script: 
  - ./mach build
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-3.9
    packages:
      - clang-3.9
